### ISSUE TITLE
how do i access datasource object inside the resolver

### ISSUE THREAD

**Issue by Yasir5247** [howtographql/typescript-apollo#6]
Hi, Thank you for the awesome tutorial.
suppose  if i have my index.ts file like this

```
import { ApolloServer } from 'apollo-server'
import { schema } from './schema'
import { context } from './context'

//configs
import appConfig from './appConfig/app'

import { SmsAPI } from './datasources/SMS/SmsAPI'

export const server = new ApolloServer({
  schema,
  dataSources: () => ({
    launchAPI: new SmsAPI(),
  }),
  context,
})

server.listen({ port: appConfig.port }).then(async ({ url }) => {
  console.log(`🚀 Server ready at: ${url}${appConfig.graphqlPath}`)
})

```
and my context file like the following. 

```
import { PrismaClient } from '@prisma/client'
import { decodeAuthHeader, AuthTokenPayload } from './utils/auth'
import { Request } from 'express'

export const prisma = new PrismaClient({
  log: ['query', 'error'],
})

export interface Context {
  prisma: PrismaClient
  userId?: number
}

export const context = ({ req }: { req: Request }): Context => {
  const token =
    req && req.headers.authorization
      ? decodeAuthHeader(req.headers.authorization)
      : null

  return {
    prisma,
    userId: token?.userId,
  }
}
```

some where in the code in my OTP Resolver function, how do i access dataSources

```
export const OTPMutations = extendType({
....
async resolve(_, args, { userId, prisma }: Context) {
//code
}
....
})
```

**Comment by TasinIshmam** [comment]
Hi @Yasir5247 :wave: 

Happy to hear that you enjoyed the tutorial :smile:  

Unfortunately, nexus does not natively support Apollo Datasources. [There's an issue about adding this feature](https://github.com/graphql-nexus/nexus/issues/505) in the nexus repo, but I don't think it's being actively developed. Nevertheless, it probably wouldn't hurt to make a comment in that issue explaining your situation. 

Based on the [Apollo docs](https://www.apollographql.com/docs/apollo-server/data/data-sources/#adding-data-sources-to-apollo-server), the `dataSources` object is attached to the `context` of every resolver by `apollo-server`. You could try adding `dataSources`   as an optional field to your `context` like this:

```typescript
export interface Context {
  prisma: PrismaClient
  userId?: number
  dataSources?: any  // feel free to manually add the specific types as well for your dataSources. 
}
```

Your resolver would look like:

```typescript
async resolve(_, args, { userId, prisma, dataSources }: Context) {
//code
}
....
})
```
I'm not aware of any other workarounds for this :disappointed:

**Comment by Yasir5247** [comment]
Thanks @TasinIshmam for the response. 
also i hope to see a example tutorial for testing a nexus and prisma api soon. :)

**Comment by TasinIshmam** [comment]
Happy to help :smile: 

> also i hope to see a example tutorial for testing a nexus and prisma api soon. :)

Testing isn't something in the works at the moment, but we are working on a chapter about deployment! That should be released soon. 

By the way, I'm closing this issue as I hope your concern has been sufficiently adressed.
